# Generated by Django 2.1.5 on 2019-02-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='link_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
